import type { IndicatorDefinition } from './types';

/**
 * Indicator catalog: definitions only (formula, unit, direction). Targets are institutional
 * configuration and live in InstitutionalConfig.targets, never here.
 */
const ccih = 'Enfermeiro CCIH';
const cme = 'Responsável técnico CME';
const surveillance = 'Vigilância ativa CCIH';

export const INDICATORS: IndicatorDefinition[] = [
  // IRAS
  { id: 'di-ipcs', name: 'Densidade de incidência de IPCS', shortName: 'IPCS', category: 'iras',
    description: 'Infecções primárias de corrente sanguínea associadas a cateter central por 1.000 cateter-dia.',
    numerator: { metric: 'iras_ipcs', label: 'IPCS confirmadas' }, denominator: { metric: 'cvc_dia', label: 'Cateter central-dia' },
    multiplier: 1000, unit: '‰', decimals: 1, periodicity: 'mensal', direction: 'lower', dataSource: surveillance,
    interpretation: 'Quanto menor, melhor. Compare com a série histórica da própria unidade.', responsibleRole: ccih, referenceId: null },
  { id: 'di-pav', name: 'Densidade de incidência de PAV', shortName: 'PAV', category: 'iras',
    description: 'Pneumonias associadas à ventilação mecânica por 1.000 ventilação mecânica-dia.',
    numerator: { metric: 'iras_pav', label: 'PAV confirmadas' }, denominator: { metric: 'vm_dia', label: 'Ventilação mecânica-dia' },
    multiplier: 1000, unit: '‰', decimals: 1, periodicity: 'mensal', direction: 'lower', dataSource: surveillance,
    interpretation: 'Quanto menor, melhor.', responsibleRole: ccih, referenceId: null },
  { id: 'di-itu', name: 'Densidade de incidência de ITU-AC', shortName: 'ITU-AC', category: 'iras',
    description: 'Infecções do trato urinário associadas a cateter por 1.000 cateter urinário-dia.',
    numerator: { metric: 'iras_itu', label: 'ITU-AC confirmadas' }, denominator: { metric: 'svd_dia', label: 'Cateter urinário-dia' },
    multiplier: 1000, unit: '‰', decimals: 1, periodicity: 'mensal', direction: 'lower', dataSource: surveillance,
    interpretation: 'Quanto menor, melhor.', responsibleRole: ccih, referenceId: null },
  { id: 'di-iras', name: 'Densidade global de IRAS', shortName: 'IRAS', category: 'iras',
    description: 'Total de IRAS confirmadas por 1.000 pacientes-dia.',
    numerator: { metric: 'iras_total', label: 'IRAS confirmadas' }, denominator: { metric: 'pacientes_dia', label: 'Pacientes-dia' },
    multiplier: 1000, unit: '‰', decimals: 1, periodicity: 'mensal', direction: 'lower', dataSource: surveillance,
    interpretation: 'Visão geral da carga de IRAS; detalhe por tipo e setor antes de concluir.', responsibleRole: ccih, referenceId: null },
  { id: 'n-iras', name: 'IRAS confirmadas', shortName: 'IRAS (n)', category: 'iras',
    description: 'Número absoluto de IRAS confirmadas no período.',
    numerator: { metric: 'iras_total', label: 'IRAS confirmadas' },
    multiplier: 1, unit: 'casos', decimals: 0, periodicity: 'mensal', direction: 'lower', dataSource: surveillance,
    interpretation: 'Contagem absoluta; não compara unidades de tamanhos diferentes.', responsibleRole: ccih, referenceId: null },
  { id: 'tx-isc-limpa', name: 'Taxa de ISC em cirurgia limpa', shortName: 'ISC limpa', category: 'iras',
    description: 'Infecções de sítio cirúrgico em cirurgias limpas por 100 cirurgias limpas.',
    numerator: { metric: 'isc_limpas', label: 'ISC em cirurgias limpas' }, denominator: { metric: 'cirurgias_limpas', label: 'Cirurgias limpas' },
    multiplier: 100, unit: '%', decimals: 1, periodicity: 'mensal', direction: 'lower', dataSource: 'Vigilância de ISC (inclui pós-alta)',
    interpretation: 'Só é definitiva após o fim da janela de vigilância pós-operatória.', responsibleRole: ccih, referenceId: null },
  { id: 'mdr-incidencia', name: 'Incidência de microrganismos multirresistentes', shortName: 'MDR', category: 'iras',
    description: 'Novos casos de MDR por 1.000 pacientes-dia.',
    numerator: { metric: 'mdr_novos', label: 'Novos casos de MDR' }, denominator: { metric: 'pacientes_dia', label: 'Pacientes-dia' },
    multiplier: 1000, unit: '‰', decimals: 1, periodicity: 'mensal', direction: 'lower', dataSource: 'Microbiologia',
    interpretation: 'Aumento sustentado sugere transmissão cruzada ou pressão seletiva.', responsibleRole: 'Médico infectologista', referenceId: null },
  // Devices
  { id: 'tu-cvc', name: 'Taxa de utilização de cateter central', shortName: 'Uso de CVC', category: 'dispositivos',
    description: 'Cateter central-dia por paciente-dia.',
    numerator: { metric: 'cvc_dia', label: 'Cateter central-dia' }, denominator: { metric: 'pacientes_dia', label: 'Pacientes-dia' },
    multiplier: 100, unit: '%', decimals: 1, periodicity: 'mensal', direction: 'lower', dataSource: 'Censo diário de dispositivos',
    interpretation: 'Reflete exposição ao risco; reavaliar indicação diariamente.', responsibleRole: ccih, referenceId: null },
  { id: 'tu-vm', name: 'Taxa de utilização de ventilação mecânica', shortName: 'Uso de VM', category: 'dispositivos',
    description: 'Ventilação mecânica-dia por paciente-dia.',
    numerator: { metric: 'vm_dia', label: 'Ventilação mecânica-dia' }, denominator: { metric: 'pacientes_dia', label: 'Pacientes-dia' },
    multiplier: 100, unit: '%', decimals: 1, periodicity: 'mensal', direction: 'lower', dataSource: 'Censo diário de dispositivos',
    interpretation: 'Reflete exposição ao risco.', responsibleRole: ccih, referenceId: null },
  { id: 'tu-svd', name: 'Taxa de utilização de cateter urinário', shortName: 'Uso de SVD', category: 'dispositivos',
    description: 'Cateter urinário-dia por paciente-dia.',
    numerator: { metric: 'svd_dia', label: 'Cateter urinário-dia' }, denominator: { metric: 'pacientes_dia', label: 'Pacientes-dia' },
    multiplier: 100, unit: '%', decimals: 1, periodicity: 'mensal', direction: 'lower', dataSource: 'Censo diário de dispositivos',
    interpretation: 'Reflete exposição ao risco.', responsibleRole: ccih, referenceId: null },
  // Surgery
  { id: 'atb-prazo', name: 'Antibioticoprofilaxia no horário', shortName: 'Profilaxia no horário', category: 'cirurgia',
    description: 'Cirurgias com dose dentro da janela institucional por cirurgias com profilaxia indicada.',
    numerator: { metric: 'profilaxia_no_prazo', label: 'Doses na janela' }, denominator: { metric: 'profilaxia_indicada', label: 'Profilaxias indicadas' },
    multiplier: 100, unit: '%', decimals: 0, periodicity: 'mensal', direction: 'higher', dataSource: 'Registro cirúrgico',
    interpretation: 'A janela usada no cálculo é a configurada pela instituição.', responsibleRole: ccih, referenceId: null },
  { id: 'atb-duracao', name: 'Antibioticoprofilaxia com duração adequada', shortName: 'Duração da profilaxia', category: 'cirurgia',
    description: 'Profilaxias encerradas dentro da duração máxima institucional.',
    numerator: { metric: 'profilaxia_ate_24h', label: 'Profilaxias no prazo' }, denominator: { metric: 'profilaxia_indicada', label: 'Profilaxias indicadas' },
    multiplier: 100, unit: '%', decimals: 0, periodicity: 'mensal', direction: 'higher', dataSource: 'Registro cirúrgico',
    interpretation: 'Duração máxima conforme configuração institucional.', responsibleRole: ccih, referenceId: null },
  // Processes
  { id: 'hm-adesao', name: 'Adesão à higiene das mãos', shortName: 'Higiene das mãos', category: 'processos',
    description: 'Ações de higiene realizadas por oportunidades observadas.',
    numerator: { metric: 'hm_acoes', label: 'Ações realizadas' }, denominator: { metric: 'hm_oportunidades', label: 'Oportunidades observadas' },
    multiplier: 100, unit: '%', decimals: 0, periodicity: 'mensal', direction: 'higher', dataSource: 'Observação direta',
    interpretation: 'Considere o número de oportunidades observadas antes de comparar setores.', responsibleRole: ccih, referenceId: null },
  { id: 'hm-consumo', name: 'Consumo de preparação alcoólica', shortName: 'Preparação alcoólica', category: 'processos',
    description: 'Mililitros de preparação alcoólica por paciente-dia.',
    numerator: { metric: 'alcool_ml', label: 'mL consumidos' }, denominator: { metric: 'pacientes_dia', label: 'Pacientes-dia' },
    multiplier: 1, unit: 'mL/pac-dia', decimals: 0, periodicity: 'mensal', direction: 'higher', dataSource: 'Almoxarifado / farmácia',
    interpretation: 'Indicador indireto de higiene das mãos.', responsibleRole: ccih, referenceId: null },
  { id: 'bundle-cvc', name: 'Adesão ao bundle de CVC', shortName: 'Bundle CVC', category: 'processos',
    description: 'Auditorias conformes do bundle de cateter central por auditorias realizadas.',
    numerator: { metric: 'bundle_cvc_conformes', label: 'Auditorias conformes' }, denominator: { metric: 'bundle_cvc_auditorias', label: 'Auditorias' },
    multiplier: 100, unit: '%', decimals: 0, periodicity: 'mensal', direction: 'higher', dataSource: 'Auditoria de bundles',
    interpretation: 'Método de cálculo definido por bundle (tudo ou nada / por item).', responsibleRole: ccih, referenceId: null },
  { id: 'bundle-vm', name: 'Adesão ao bundle de VM', shortName: 'Bundle VM', category: 'processos',
    description: 'Auditorias conformes do bundle de ventilação mecânica por auditorias realizadas.',
    numerator: { metric: 'bundle_vm_conformes', label: 'Auditorias conformes' }, denominator: { metric: 'bundle_vm_auditorias', label: 'Auditorias' },
    multiplier: 100, unit: '%', decimals: 0, periodicity: 'mensal', direction: 'higher', dataSource: 'Auditoria de bundles',
    interpretation: 'Método de cálculo definido por bundle.', responsibleRole: ccih, referenceId: null },
  { id: 'bundle-svd', name: 'Adesão ao bundle de cateter urinário', shortName: 'Bundle SVD', category: 'processos',
    description: 'Auditorias conformes do bundle de cateter urinário por auditorias realizadas.',
    numerator: { metric: 'bundle_svd_conformes', label: 'Auditorias conformes' }, denominator: { metric: 'bundle_svd_auditorias', label: 'Auditorias' },
    multiplier: 100, unit: '%', decimals: 0, periodicity: 'mensal', direction: 'higher', dataSource: 'Auditoria de bundles',
    interpretation: 'Método de cálculo definido por bundle.', responsibleRole: ccih, referenceId: null },
  // Antimicrobials
  { id: 'atm-ddd', name: 'Consumo de antimicrobianos', shortName: 'DDD/1.000 pac-dia', category: 'antimicrobianos',
    description: 'Doses diárias definidas por 1.000 pacientes-dia.',
    numerator: { metric: 'atm_ddd', label: 'DDD dispensadas' }, denominator: { metric: 'pacientes_dia', label: 'Pacientes-dia' },
    multiplier: 1000, unit: 'DDD/1.000', decimals: 0, periodicity: 'mensal', direction: 'lower', dataSource: 'Farmácia',
    interpretation: 'Acompanhar tendência; meta depende do perfil institucional.', responsibleRole: 'Médico infectologista', referenceId: null },
  // CME
  { id: 'cme-ciclos-conformes', name: 'Ciclos de esterilização conformes', shortName: 'Ciclos conformes', category: 'cme',
    description: 'Ciclos sem não conformidade por ciclos realizados.',
    numerator: { metric: 'cme_ciclos_conformes', label: 'Ciclos conformes' }, denominator: { metric: 'cme_ciclos', label: 'Ciclos realizados' },
    multiplier: 100, unit: '%', decimals: 1, periodicity: 'mensal', direction: 'higher', dataSource: 'Registro de ciclos CME',
    interpretation: 'Toda não conformidade deve ter análise registrada.', responsibleRole: cme, referenceId: null },
  { id: 'cme-ciclos', name: 'Ciclos de esterilização realizados', shortName: 'Ciclos realizados', category: 'cme',
    description: 'Número de ciclos de esterilização realizados no período.',
    numerator: { metric: 'cme_ciclos', label: 'Ciclos realizados' },
    multiplier: 1, unit: 'ciclos', decimals: 0, periodicity: 'mensal', direction: 'higher', dataSource: 'Registro de ciclos CME',
    interpretation: 'Volume de produção; não é meta de qualidade.', responsibleRole: cme, referenceId: null },
  { id: 'cme-ciclos-nao-conformes', name: 'Ciclos de esterilização não conformes', shortName: 'Ciclos não conformes', category: 'cme',
    description: 'Ciclos com não conformidade (parâmetro físico, teste ou registro) por ciclos realizados.',
    numerator: { metric: 'cme_ciclos_nao_conformes', label: 'Ciclos não conformes' }, denominator: { metric: 'cme_ciclos', label: 'Ciclos realizados' },
    multiplier: 100, unit: '%', decimals: 1, periodicity: 'mensal', direction: 'lower', dataSource: 'Registro de ciclos CME',
    interpretation: 'Cada ciclo não conforme deve ter causa e ação registradas.', responsibleRole: cme, referenceId: null },
  { id: 'cme-iq-conformes', name: 'Indicadores químicos conformes', shortName: 'IQ conformes', category: 'cme',
    description: 'Indicadores químicos (classes 1 a 6) com viragem conforme por indicadores lidos.',
    numerator: { metric: 'cme_iq_conformes', label: 'IQ conformes' }, denominator: { metric: 'cme_iq_lidos', label: 'IQ lidos' },
    multiplier: 100, unit: '%', decimals: 1, periodicity: 'mensal', direction: 'higher', dataSource: 'Registro de testes CME',
    interpretation: 'Viragem não conforme exige reprocessamento do pacote.', responsibleRole: cme, referenceId: null },
  { id: 'cme-cargas-retidas', name: 'Cargas retidas', shortName: 'Cargas retidas', category: 'cme',
    description: 'Cargas retidas (aguardando resultado ou em análise) por cargas processadas.',
    numerator: { metric: 'cme_cargas_retidas', label: 'Cargas retidas' }, denominator: { metric: 'cme_cargas', label: 'Cargas processadas' },
    multiplier: 100, unit: '%', decimals: 1, periodicity: 'mensal', direction: 'lower', dataSource: 'Liberação de cargas',
    interpretation: 'Inclui retenções previstas pela política (implantáveis aguardando IB).', responsibleRole: cme, referenceId: null },
  { id: 'cme-reprocessamento', name: 'Cargas reprocessadas', shortName: 'Reprocessamento', category: 'cme',
    description: 'Cargas enviadas a reprocessamento por cargas processadas.',
    numerator: { metric: 'cme_cargas_reprocessadas', label: 'Cargas reprocessadas' }, denominator: { metric: 'cme_cargas', label: 'Cargas processadas' },
    multiplier: 100, unit: '%', decimals: 1, periodicity: 'mensal', direction: 'lower', dataSource: 'Liberação de cargas',
    interpretation: 'Aumento sugere falha de preparo, embalagem ou equipamento.', responsibleRole: cme, referenceId: null },
  { id: 'cme-nao-conformidades', name: 'Não conformidades da CME', shortName: 'NC da CME', category: 'cme',
    description: 'Não conformidades registradas no processamento no período.',
    numerator: { metric: 'cme_nao_conformidades', label: 'Não conformidades' },
    multiplier: 1, unit: 'registros', decimals: 0, periodicity: 'mensal', direction: 'lower', dataSource: 'Registro de não conformidades CME',
    interpretation: 'Analisar por etapa do processo (Pareto).', responsibleRole: cme, referenceId: null },
  { id: 'cme-bowie-dick', name: 'Bowie-Dick aprovado', shortName: 'Bowie-Dick', category: 'cme',
    description: 'Testes de Bowie-Dick aprovados por testes realizados.',
    numerator: { metric: 'cme_bd_aprovados', label: 'Testes aprovados' }, denominator: { metric: 'cme_bd_realizados', label: 'Testes realizados' },
    multiplier: 100, unit: '%', decimals: 1, periodicity: 'mensal', direction: 'higher', dataSource: 'Registro de testes CME',
    interpretation: 'Reprovação exige bloqueio do equipamento.', responsibleRole: cme, referenceId: null },
  { id: 'cme-ib-negativo', name: 'Indicador biológico negativo', shortName: 'IB negativo', category: 'cme',
    description: 'Cargas com indicador biológico negativo por cargas monitoradas.',
    numerator: { metric: 'cme_ib_negativos', label: 'IB negativos' }, denominator: { metric: 'cme_ib_monitorados', label: 'IB monitorados' },
    multiplier: 100, unit: '%', decimals: 1, periodicity: 'mensal', direction: 'higher', dataSource: 'Registro de testes CME',
    interpretation: 'IB positivo exige recolhimento e rastreio de pacientes expostos.', responsibleRole: cme, referenceId: null },
  { id: 'cme-cargas-liberadas', name: 'Cargas liberadas', shortName: 'Cargas liberadas', category: 'cme',
    description: 'Cargas liberadas por cargas processadas.',
    numerator: { metric: 'cme_cargas_liberadas', label: 'Cargas liberadas' }, denominator: { metric: 'cme_cargas', label: 'Cargas processadas' },
    multiplier: 100, unit: '%', decimals: 1, periodicity: 'mensal', direction: 'higher', dataSource: 'Liberação de cargas',
    interpretation: 'Cargas retidas aguardando IB não são falha.', responsibleRole: cme, referenceId: null },
  { id: 'cme-rastreabilidade', name: 'Caixas rastreadas até o paciente', shortName: 'Rastreabilidade', category: 'cme',
    description: 'Caixas com vínculo ciclo → cirurgia → prontuário por caixas utilizadas.',
    numerator: { metric: 'cme_caixas_rastreadas', label: 'Caixas rastreadas' }, denominator: { metric: 'cme_caixas_usadas', label: 'Caixas utilizadas' },
    multiplier: 100, unit: '%', decimals: 1, periodicity: 'mensal', direction: 'higher', dataSource: 'Rastreabilidade CME',
    interpretation: 'Toda caixa sem vínculo é uma lacuna de rastreabilidade.', responsibleRole: cme, referenceId: null },
  // Management
  { id: 'treinamento-cobertura', name: 'Cobertura de treinamentos', shortName: 'Treinamentos', category: 'gestao',
    description: 'Colaboradores treinados por público-alvo dos treinamentos obrigatórios.',
    numerator: { metric: 'treinamento_concluidos', label: 'Treinados' }, denominator: { metric: 'treinamento_publico', label: 'Público-alvo' },
    multiplier: 100, unit: '%', decimals: 0, periodicity: 'mensal', direction: 'higher', dataSource: 'Gestão de treinamentos',
    interpretation: 'Considere vencimentos de reciclagem.', responsibleRole: ccih, referenceId: null },
  { id: 'investigacoes-abertas', name: 'Investigações abertas', shortName: 'Investigações abertas', category: 'gestao',
    description: 'Suspeitas de IRAS ainda sem conclusão no fim do período.',
    numerator: { metric: 'investigacoes_abertas', label: 'Investigações abertas' },
    multiplier: 1, aggregation: 'estoque', unit: 'casos', decimals: 0, periodicity: 'mensal', direction: 'lower', dataSource: surveillance,
    interpretation: 'Investigações antigas atrasam o fechamento dos indicadores.', responsibleRole: ccih, referenceId: null },
];

const BY_ID = new Map(INDICATORS.map((d) => [d.id, d]));

export function getIndicator(id: string): IndicatorDefinition {
  const def = BY_ID.get(id);
  if (!def) throw new Error(`Indicador desconhecido: ${id}`);
  return def;
}
